language: go

go:
- "1.7"
- tip

# Only applicable to our fork
install: |
  cd ../.. && \
  mv alphagov 18F && \
  cd 18F && \
  mv paas-cdn-broker cf-cdn-service-broker && \
  cd cf-cdn-service-broker

# Skip vendor tests
script: go test -v $(go list ./... | grep -v /vendor/)
